[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = partitions.csv
monitor_speed = 115200
monitor_port = COM20
upload_port = COM20
upload_speed = 460800
upload_resetmethod = nodemcu
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DSEED_FROM_SECRETS
    -DDEVICE_NAME='"2021AT4"'
build_src_filter = -<*> +<main.cpp> +<ble_transfer.cpp>
lib_deps =
    adafruit/RTClib@^2.1.1
    adafruit/Adafruit MQTT Library@^2.5.4
    esphome/AsyncTCP-esphome@^2.0.0
    esphome/ESPAsyncWebServer-esphome@^3.1.0
    bblanchon/ArduinoJson@^7.0.0
    h2zero/NimBLE-Arduino@^1.4.2
lib_ignore =
    WiFiNINA
    Adafruit WiFiNINA
    WiFiNINA_-_Adafruit_Fork
    WiFi101

[env:voltmon-test]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = partitions.csv
monitor_speed = 115200
monitor_port = COM19
upload_speed = 460800
upload_resetmethod = nodemcu
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DSEED_FROM_SECRETS
    -DVOLTMON_TEST
    -DDEVICE_NAME='"TestDevice"'
build_src_filter = -<*> +<test_main.cpp>
lib_deps =
    adafruit/Adafruit MQTT Library@^2.5.4
    esphome/AsyncTCP-esphome@^2.0.0
    esphome/ESPAsyncWebServer-esphome@^3.1.0
    bblanchon/ArduinoJson@^7.0.0
    h2zero/NimBLE-Arduino@^1.4.2
lib_ignore =
    WiFiNINA
    Adafruit WiFiNINA
    WiFiNINA_-_Adafruit_Fork
    WiFi101

[env:voltmon-collector]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = partitions.csv
monitor_speed = 115200
monitor_port = COM3
upload_speed = 460800
upload_resetmethod = nodemcu
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDEVICE_NAME='"Collector"'
build_src_filter = -<*> +<collector_main.cpp>
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
    adafruit/Adafruit MQTT Library@^2.5.4
    bblanchon/ArduinoJson@^7.0.0
    h2zero/NimBLE-Arduino@^1.4.2
lib_ignore =
    WiFiNINA
    Adafruit WiFiNINA
    WiFiNINA_-_Adafruit_Fork
    WiFi101